---

# ------------------------------------------------------------------------
# NIS HANDLERS
# ------------------------------------------------------------------------

- name: restart network
  service: name=network state=restarted sleep=5

- name: restart ypbind
  service: name=ypbind state=restarted

- name: restart rpcbind
  service: name=rpcbind state=restarted